server:
  port : 8086

spring:
  application:
    name: client-service

  data:
    mongo:
      repositories:
        type: reactive
    mongodb:
      authSource: admin
      database: auth
      user: root
      password: root
      host: localhost
      port: 27018

debug: false
