security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: xxx
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true