security:
  oauth2:
    client:
      clientId: smtp-service
      clientSecret: xxx
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: templatebuilder
      uri: mongodb://test:test@localhost:27018/templatebuilder

server:
  servlet:
    context-path: /
  port: 6002

management:
  endpoints:
    web:
      exposure:
        include: "*"
