security:
  oauth2:
    client:
      clientId: template-builder-service
      clientSecret: xxx
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      database: templatebuilder
      uri: mongodb://root:root@localhost:27017/templatebuilder?authSource=admin

server:
  servlet:
    context-path: /
  port: 6002

management:
  endpoints:
    web:
      exposure:
        include: "*"
